FIND_PATH(SSVJSONCPP_INCLUDE_DIR
  NAMES SSVJsonCpp/SSVJsonCpp.h
  PATH_SUFFIXES include/
  PATHS "${PROJECT_SOURCE_DIR}/../SSVJsonCpp/"
  "${PROJECT_SOURCE_DIR}/extlibs/SSVJsonCpp/"
  ${SSVJSONCPP_ROOT}
  $ENV{SSVJSONCPP_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound SSVJsonCpp include at: ${SSVJSONCPP_INCLUDE_DIR}.\n")

IF(SSVJSONCPP_INCLUDE_DIR)
  SET(SSVJSONCPP_FOUND TRUE)
ELSE(SSVJSONCPP_INCLUDE_DIR)
  SET(SSVJSONCPP_FOUND FALSE)
ENDIF(SSVJSONCPP_INCLUDE_DIR)

IF(SSVJSONCPP_FOUND)
  MESSAGE(STATUS "Found SSVJsonCpp in ${SSVJSONCPP_INCLUDE_DIR}")
ELSE(SSVJSONCPP_FOUND)
  IF(SSVJSONCPP_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SSVJsonCpp library")
  ENDIF(SSVJSONCPP_FIND_REQUIRED)
ENDIF(SSVJSONCPP_FOUND)

MARK_AS_ADVANCED(
  SSVJSONCPP_INCLUDE_DIR
)
